import { Pipe, PipeTransform, inject } from "@angular/core";
import { SocialService } from "./social.service";
export const HINDI: Record<string, string> = {
  sit: "बैठें",
  rest: "आराम",
  sleep: "सोएँ",
  study: "पढ़ाई",
  work: "काम",
  eat: "खाएँ",
  approach: "पास जा रहे हैं",
  active: "जारी",
  "Room furniture": "कमरे का फ़र्नीचर",
  chair: "कुर्सी",
  sofa: "सोफ़ा",
  desk: "मेज़",
  bed: "बिस्तर",
  counter: "काउंटर",
  plant: "पौधा",
  lamp: "दीपक",
  game: "खेलें",
  "Delete home permanently": "घर हमेशा के लिए मिटाएँ",
  "Skin tone": "त्वचा का रंग",
  "Hair color": "बालों का रंग",
  "Hair style": "बालों की शैली",
  Outfit: "पोशाक",
  Porcelain: "हल्का",
  Peach: "आड़ू",
  Honey: "शहद",
  "Warm brown": "हल्का भूरा",
  "Deep brown": "गहरा भूरा",
  Ink: "काला",
  Brown: "भूरा",
  Chestnut: "कस्तूरी",
  Gold: "सुनहरा",
  Silver: "चाँदी",
  Rose: "गुलाबी",
  Short: "छोटे",
  Long: "लंबे",
  Bun: "जूड़ा",
  Lavender: "लैवेंडर",
  Blue: "नीला",
  Green: "हरा",
  Amber: "अंबर",
  Slate: "स्लेटी",
  "Your space, your pace": "आपकी जगह, आपकी रफ़्तार",
  "Make yourself at home.": "इसे अपना घर समझें।",
  "Choose your language and avatar. You can change these later.":
    "अपनी भाषा और अवतार चुनें। इन्हें बाद में बदल सकते हैं।",
  "Your appearance never changes your age-group access. Activities and contact details stay private by default.":
    "अवतार बदलने से आयु वर्ग नहीं बदलता। गतिविधियाँ और संपर्क जानकारी डिफ़ॉल्ट रूप से निजी हैं।",
  "Enter Timrom": "Timrom में आएँ",
  "Date of birth": "जन्म तिथि",
  "Local age fixture only; this is not identity or guardian verification.":
    "यह स्थानीय आयु परीक्षण है; पहचान या अभिभावक का सत्यापन नहीं।",
  "Home paused": "घर अस्थायी रूप से बंद",
  "An eligible member must accept ownership before this home reopens.":
    "घर दोबारा खुलने से पहले योग्य सदस्य को स्वामित्व स्वीकार करना होगा।",
  "Successor username": "नए मालिक का यूज़रनेम",
  "Offer ownership": "स्वामित्व की पेशकश करें",
  "Accept ownership": "स्वामित्व स्वीकार करें",
  "Borrowed items return to their owners. Home-owned items and room conversations are deleted.":
    "उधार की वस्तुएँ मालिकों को लौटेंगी। घर की वस्तुएँ और कमरों की बातचीत मिट जाएगी।",
  "Type the home name": "घर का नाम लिखें",
  "Not linked": "जुड़ा नहीं है",
  "Contact change": "संपर्क बदलें",
  "Replace existing contact": "मौजूदा संपर्क बदलें",
  "Password (only when adding your first email)":
    "पासवर्ड (पहला ईमेल जोड़ते समय)",
  "Audio output": "आवाज़ सुनने का उपकरण",
  Speaker: "स्पीकर",
  "This browser uses the system audio output.":
    "यह ब्राउज़र सिस्टम के आवाज़ उपकरण का उपयोग करता है।",
  "Local preview": "स्थानीय पूर्वावलोकन",
  "Visual demo": "दृश्य नमूना",
  "A place for your people": "अपनों के लिए एक जगह",
  "Welcome back.": "फिर से स्वागत है।",
  "Come on in.": "आपका स्वागत है।",
  Email: "ईमेल",
  Mobile: "मोबाइल",
  Password: "पासवर्ड",
  "Display name": "दिखने वाला नाम",
  "Age group": "आयु वर्ग",
  "18+ adults": "18+ वयस्क",
  "13–17 teens": "13–17 किशोर",
  "Verification code": "सत्यापन कोड",
  "Sign in": "लॉग इन",
  "Create account": "खाता बनाएँ",
  "Get test code": "परीक्षण कोड पाएँ",
  Verify: "सत्यापित करें",
  "Please wait…": "कृपया प्रतीक्षा करें…",
  "Homes for conversation, focus and everything in between.":
    "बातचीत, पढ़ाई, काम और साथ बिताने के लिए घर।",
  "Private contact details · Separate teen and adult spaces":
    "निजी संपर्क जानकारी · किशोरों और वयस्कों के लिए अलग स्थान",
  "Find your people.": "अपने लोगों से मिलें।",
  "Discover a community, use an invitation, or create a home.":
    "समुदाय खोजें, निमंत्रण इस्तेमाल करें या घर बनाएँ।",
  "Create home": "घर बनाएँ",
  "Create a home": "घर बनाएँ",
  "No personal house is created automatically.":
    "निजी घर अपने आप नहीं बनाया जाता।",
  "No homes yet. Create one or use an invitation.":
    "अभी कोई घर नहीं है। घर बनाएँ या निमंत्रण इस्तेमाल करें।",
  "Enter a home to join its conversation.":
    "बातचीत में शामिल होने के लिए घर में प्रवेश करें।",
  "All communities": "सभी समुदाय",
  "All regions": "सभी क्षेत्र",
  Asia: "एशिया",
  Africa: "अफ्रीका",
  Europe: "यूरोप",
  "North America": "उत्तरी अमेरिका",
  "South America": "दक्षिणी अमेरिका",
  Oceania: "ओशिनिया",
  Country: "देश",
  State: "राज्य",
  City: "शहर",
  Region: "क्षेत्र",
  "Invitation code": "निमंत्रण कोड",
  "Join by invite": "निमंत्रण से जुड़ें",
  "Home rules": "घर के नियम",
  "Accept home rules & join": "नियम स्वीकार करके जुड़ें",
  "Walk to gate": "दरवाज़े तक चलें",
  "Rotate globe": "ग्लोब घुमाएँ",
  Name: "नाम",
  "Free template": "मुफ़्त नमूना",
  Hangout: "मिलना-जुलना",
  Study: "पढ़ाई",
  Gaming: "गेमिंग",
  Work: "काम",
  "Account & privacy": "खाता और गोपनीयता",
  "Home rules & management": "घर के नियम और प्रबंधन",
  "⌗ Edit floor plan": "⌗ घर का नक्शा बदलें",
  "Opt in to room-based tracking": "कमरे के आधार पर गतिविधि दर्ज करें",
  "Opt in to furniture-based tracking":
    "फ़र्नीचर के उपयोग से गतिविधि दर्ज करें",
  "Remember automatic voice joining": "अपने आप वॉइस में जुड़ना याद रखें",
  "Voice & video devices": "आवाज़ और वीडियो उपकरण",
  "Refresh devices": "उपकरण सूची ताज़ा करें",
  Microphone: "माइक्रोफ़ोन",
  Camera: "कैमरा",
  "System default": "डिफ़ॉल्ट उपकरण",
  "Low bandwidth (next camera start)": "कम डेटा (अगली बार कैमरा चालू होने पर)",
  "Capacity · 0 = unlimited": "क्षमता · 0 = असीमित",
  Capacity: "क्षमता",
  "Save capacity": "क्षमता सहेजें",
  "Voice mode": "वॉइस का तरीका",
  "Open conversation": "खुली बातचीत",
  "Moderated speakers": "संचालक द्वारा चुने वक्ता",
  "Quiet room": "शांत कमरा",
  "Lock new entry": "नया प्रवेश रोकें",
  "Add connected room": "जुड़ा हुआ कमरा जोड़ें",
  "Add room": "कमरा जोड़ें",
  Activity: "गतिविधि",
  "Home roles": "घर की भूमिकाएँ",
  Member: "सदस्य",
  Admin: "प्रशासक",
  Moderator: "संचालक",
  "History & day/week totals": "इतिहास और दिन/सप्ताह का समय",
  "Start activity": "गतिविधि शुरू करें",
  "Start privately": "निजी रूप से शुरू करें",
  "Stop activity": "गतिविधि रोकें",
  "Gifts & loans": "उपहार और उधार",
  "Apply finish": "रंग लगाएँ",
  "Place / move": "रखें / स्थान बदलें",
  Store: "संग्रह में रखें",
  Catalog: "वस्तुओं की सूची",
  "Buy one": "एक ख़रीदें",
  "Join voice": "वॉइस में जुड़ें",
  Leave: "छोड़ें",
  "Say hello to the room.": "कमरे में सभी को नमस्ते कहें।",
  "Replying to a message": "संदेश का उत्तर",
  "Stand / finish action": "उठें / क्रिया समाप्त करें",
  Cancel: "रद्द करें",
  Save: "सहेजें",
  "Continue on this device": "इस उपकरण पर जारी रखें",
  "The world is active on another device.": "दुनिया दूसरे उपकरण पर सक्रिय है।",
  "People & messages": "लोग और संदेश",
  "Find by username": "यूज़रनेम से खोजें",
  "Add friend": "मित्र जोड़ें",
  Accept: "स्वीकार करें",
  Decline: "अस्वीकार करें",
  Message: "संदेश",
  "Direct conversation": "निजी बातचीत",
  Send: "भेजें",
  "Your avatar": "आपका अवतार",
  "Body style": "शरीर की शैली",
  Miniature: "छोटी शैली",
  Mature: "परिपक्व शैली",
  "Save avatar": "अवतार सहेजें",
  Language: "भाषा",
  "Reduce decorative motion": "सजावटी हलचल कम करें",
  "In-app notifications": "ऐप की सूचनाएँ",
  "Blocked accounts": "ब्लॉक किए खाते",
  Unblock: "ब्लॉक हटाएँ",
  Notifications: "सूचनाएँ",
  "Mark all read": "सभी पढ़े हुए चिह्नित करें",
  "You’re all caught up.": "कोई नई सूचना नहीं है।",
  "In this room": "इस कमरे में",
  Block: "ब्लॉक करें",
  Report: "रिपोर्ट करें",
  Mute: "आवाज़ बंद करें",
  Kick: "कमरे से हटाएँ",
  "10 min timeout": "10 मिनट संदेश रोकें",
  "Ban…": "प्रतिबंध…",
  "Ban this person from the home?": "इस व्यक्ति को घर से प्रतिबंधित करें?",
  Reason: "कारण",
  "Confirm ban": "प्रतिबंध की पुष्टि करें",
  "What happened?": "क्या हुआ?",
  "Submit report": "रिपोर्ट भेजें",
  "Moderation history": "संचालन का इतिहास",
  "Furniture sharing": "फ़र्नीचर साझा करें",
  Furniture: "फ़र्नीचर",
  "Receiving home": "प्राप्त करने वाला घर",
  Offer: "प्रस्ताव",
  "Lend — reclaimable": "उधार — वापस ले सकते हैं",
  "Donate — permanent while home exists": "दान — घर मौजूद रहने तक स्थायी",
  "Send offer": "प्रस्ताव भेजें",
  "Pending offers": "लंबित प्रस्ताव",
  Loans: "उधार दी वस्तुएँ",
  Description: "विवरण",
  "Community latitude": "समुदाय का अक्षांश",
  "Community longitude": "समुदाय का देशांतर",
  "Save details": "विवरण सहेजें",
  "Request public listing review": "सार्वजनिक सूची के लिए समीक्षा माँगें",
  "Room access": "कमरे में प्रवेश",
  "Who can enter": "कौन प्रवेश कर सकता है",
  "All members": "सभी सदस्य",
  "Selected members and moderators": "चुने सदस्य और संचालक",
  "Save room access": "प्रवेश नियम सहेजें",
  Ownership: "स्वामित्व",
  "Offer ownership to": "स्वामित्व का प्रस्ताव दें",
  "Send transfer request": "हस्तांतरण अनुरोध भेजें",
  "Delete home": "घर मिटाएँ",
  "Delete permanently": "स्थायी रूप से मिटाएँ",
  "Platform review": "प्लेटफ़ॉर्म समीक्षा",
  Approve: "मंज़ूर करें",
  Reject: "नामंज़ूर करें",
  Reports: "रिपोर्ट",
  "Activity history": "गतिविधियों का इतिहास",
  Started: "शुरुआत",
  Ended: "समाप्ति",
  Audience: "किसे दिखाई दे",
  "Add past activity": "पिछली गतिविधि जोड़ें",
  Delete: "मिटाएँ",
  "Confirm identity": "पहचान की पुष्टि करें",
  "Existing password": "वर्तमान पासवर्ड",
  "Registered-contact test code": "पंजीकृत संपर्क का परीक्षण कोड",
  "Add second contact": "दूसरा संपर्क जोड़ें",
  Contact: "संपर्क",
  "Password for new email": "नए ईमेल का पासवर्ड",
  "Verify new contact": "नया संपर्क सत्यापित करें",
  "Download my data": "मेरा डेटा डाउनलोड करें",
  "Delete account permanently": "खाता स्थायी रूप से मिटाएँ",
  "Type your username": "अपना यूज़रनेम लिखें",
  "Delete my account": "मेरा खाता मिटाएँ",
  Code: "कोड",
  "Verify code": "कोड सत्यापित करें",
  "Identity confirmed for five minutes.":
    "पाँच मिनट के लिए पहचान की पुष्टि हुई।",
  "Home builder": "घर का नक्शा",
  "Reload saved layout": "सहेजा नक्शा फिर खोलें",
  "↶ Undo": "↶ बदलाव वापस लें",
  Doorways: "दरवाज़े",
  From: "यहाँ से",
  To: "यहाँ तक",
  "Connect touching rooms": "पास के कमरे जोड़ें",
  "Add doorway at these tiles": "चुनी जगह पर दरवाज़ा जोड़ें",
  "History is self-reported. Edits and offline time never earn rewards.":
    "इतिहास स्वयं दर्ज किया जाता है। बदलाव और ऑफ़लाइन समय से पुरस्कार नहीं मिलते।",
  "Contact details stay private. Local test codes do not send email or SMS.":
    "संपर्क विवरण निजी रहते हैं। स्थानीय परीक्षण कोड ईमेल या SMS नहीं भेजते।",
  "Optional community affiliation, never a member’s address.":
    "समुदाय का वैकल्पिक क्षेत्र, किसी सदस्य का पता नहीं।",
  "Gifts transfer ownership after the home accepts. Loans remain yours and can be reclaimed.":
    "घर के स्वीकार करने पर उपहार का स्वामित्व बदलता है। उधार की वस्तुएँ आपकी रहती हैं और वापस ली जा सकती हैं।",
  "Returns loans and surviving donations to their original owners. This permanently removes rooms and chat.":
    "उधार और बची दान की वस्तुएँ मूल मालिकों को लौटेंगी। कमरे और बातचीत स्थायी रूप से मिट जाएँगे।",
  "Transfer or delete owned homes first. Your messages, contacts, history and inventory will be removed.":
    "पहले अपने घर हस्तांतरित करें या मिटाएँ। आपके संदेश, संपर्क, इतिहास और वस्तुएँ हट जाएँगी।",
  "Edit a draft, then publish it together. Occupied rooms must be empty before resizing or moving.":
    "पहले मसौदा बदलें, फिर सारे बदलाव लागू करें। कमरा खिसकाने या आकार बदलने से पहले उसे खाली करें।",
};
@Pipe({ name: "ui", pure: false })
export class UiTextPipe implements PipeTransform {
  private api = inject(SocialService);
  transform(value: string) {
    return this.api.language() === "hi" ? HINDI[value] || value : value;
  }
}
